### ISSUE TITLE
PDF errors

### ISSUE THREAD

**Issue by jshemas** [jnutter/phantom-pdf#12]
After updating to the latest version of this package, I now get this error:

```
Checking if phantomjs is installed in provided path:  phantomjs
Phantom booted

ReferenceError: Can't find variable: system


  phantomjs://code/index.js:9 in global code
```

**Comment by jshemas** [comment]
I think its coming from `phantomArgs = system.args;` in `phantom-pdf/phantom/index.js`

**Comment by jshemas** [comment]
You might have to do something like...

```
var system = require('system');
phantomArgs = system.args;
```

Info: http://stackoverflow.com/questions/20903109/phantomjs-command-line-variable

**Comment by jshemas** [comment]
After fixing that, now I get this:

```
Checking if phantomjs is installed in provided path:  phantomjs
Phantom booted

Reading config files
Phantom booted
Reading config files
Removing config files
Loading page

PDF ERROR: { code: 1, error: null }
```

**Comment by jshemas** [comment]
Forgot to say i'm running Node.js version `v5.8.0` with the latest version of Phantom on OSX `10.11.13`

Ping'in @jnutter @manikandants for visibility.

**Comment by jnutter** [comment]
Trying linking to the absolute path of phantom? To get this just type ``` which phantomjs ```. If that doesnt come up with anything, then you are going to have to track it down yourself.

**Comment by jshemas** [comment]
Where should I be linking the path?

Running `which phantomjs` outputs: `/usr/local/bin/phantomjs`

**Comment by jnutter** [comment]
In the manifest add:

```phantomjsPath: '/usr/local/bin/phantomjs'```

Please see README for the full example of the manifest

**Comment by jshemas** [comment]
Add.

Now I get the error:
```
Checking if phantomjs is installed in provided path:  /usr/local/bin/phantomjs
Can't open '/Users/project_name/node_modules/phantom-pdf/lib/../phantom/index.js'
```

Then it for some reason deletes `index.js`.

Dumb question: Does this library still work for you?

**Comment by jnutter** [comment]
Right now we are using version 0.3.0 and are one Phantom 1 still.

**Comment by gcmeen** [comment]
Checking if phantomjs is installed in provided path:  phantomjs
{ error: 'PhantomJS not installed' }

i have installed phantomjs but although i got the error that phantomjs not install

**Comment by jnutter** [comment]
You need to tell phantom-pdf where it is. Try type `which phantomjs` and then update `phantomjsPath` with the result.

**Comment by gcmeen** [comment]
can not get path of phantomjs when i am running 'which phantomjs' command i got the following output :

'which' is not recognized as an internal or external command,
operable program or batch file

where should i type 'which phantomjs'???

**Comment by gcmeen** [comment]
i have fixed previous error but now i am getting following error when i am going to generate pdf:

Checking if phantomjs is installed in provided path:  phantomjs
Phantom booted

ReferenceError: Can't find variable: system
  phantomjs://code/index.js:9 in global code

ReferenceError: Can't find variable: process
  phantomjs://platform/path.js:26 

what should i do to fix it?

**Comment by jshemas** [comment]
@gcmeen This module doesn't work with new versions of phantomjs. I would suggest finding a new package.
