### ISSUE TITLE
Add less issue

### ISSUE THREAD

**Issue by idanblich** [jnutter/phantom-pdf#3]
Hi, 
Im trying to add less/css file but have some issues with it:
i start by adding Less file but that made the header and footer to disappear , the less file did affect the body.
then i tryed to add NODE_ENV=test  and only add css , the code stop after the "no processing needed" message ( didn't show any fs.read comment to this option ) 
can you please provide any solution ? 
Thank you for your help.
Idan

**Comment by jnutter** [comment]
Sorry for the late reply. I thought I got updates when there was a new issue. If you using less then you need to add ```less: rootDir + '/less/styles.less'``` in the manifest.
